[package]
name = "zxhn_h108n_wifi_password_disclosure"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.90"
colored = "2.1.0"
regex = "1.11.0"
ureq = "2.10.1"
